/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - WHERE, GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by city
SELECT 
    city,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY city
ORDER BY total_customers;

-- Find total products by category
SELECT
    product_category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY product_category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    product_category,
    AVG(unit_price) AS avg_cost
FROM gold.dim_products
GROUP BY product_category
ORDER BY avg_cost ASC;

-- What is the total revenue generated for each category?
SELECT 
    p.product_category,
    SUM(s.total_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
WHERE s.order_status = 'Completed'
GROUP BY p.product_category
ORDER BY total_revenue ASC;

-- What is the total revenue generated by each customer?
SELECT
    customer_name,
    SUM(total_amount) AS total_revenue
FROM gold.fact_sales
WHERE order_status = 'Completed'
GROUP BY customer_name
ORDER BY total_revenue;

-- What is the distribution of sold items across city?
SELECT
    c.city,
    SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
WHERE s.order_status = 'Completed'
GROUP BY c.city
ORDER BY total_sold_items DESC;